### ISSUE TITLE
Add to instructions to request review before merge

### ISSUE THREAD

**Issue by skyetim** [jtr13/cc19#131]

**Comment by jtr13** [comment]
Not sure what you mean by this.

**Comment by skyetim** [comment]
we want to review the changes maintainers make in the pull request before we finally merge it. It's hard to revert things after the pull request is merged to master branch

**Comment by jtr13** [comment]
Makes sense. You could have maintainers start by suggesting changes which they can do without write access to the repo -- anyone can comment. Then if you're satisfied that they're doing things properly, they can be given write access. That said, things can be fixed -- it's not the end of the world if mistakes happen.
