### ISSUE TITLE
Travis failure: parser error

### ISSUE THREAD

**Issue by bojum** [jtr13/cc19#161]
On #114 and #54 

![Screen Shot 2019-11-01 at 11 29 37 PM](https://user-images.githubusercontent.com/54489225/68085585-70635280-fe10-11e9-8c1f-b4de6290a2b6.png)

**Comment by jtr13** [comment]
This is the old "select" conflict problem that is fixed now. I think if you merge master back into the PR, the problem will go away.

**Comment by bojum** [comment]
It's gone. Thank you.
