### ISSUE TITLE
Travis build problem

### ISSUE THREAD

**Issue by jtr13** [jtr13/cc19#180]
There's a strange leaflet error similar to the problems described here: https://github.com/rstudio/bookdown/issues/15,

that is causing Travis to fail both on master and organization branch (https://travis-ci.com/jtr13/cc19/builds/136839350)

**Comment by skyetim** [comment]
travis is down again, but this time I think it's travis problem, because I received the same error for my final project as well.

**Comment by jtr13** [comment]
Yeah, I'm quite sure it's Travis, as it's failing very quickly before it gets to anything related to the book. A new version of R just came out, maybe it's connected.

**Comment by jtr13** [comment]
Fixed now
