### ISSUE TITLE
Add section for maintainers

### ISSUE THREAD

**Issue by jtr13** [jtr13/cc19#26]
Add a section to Chapter 1 with instructions for maintainers -- this will also be helpful for contributors to see how their work will be evaluated. It will explain how the site is maintained, including a checklist for submissions, instructions for what to do with submissions that don't meet requirements, the meaning of the labels, and how assignments work.

**Comment by skyetim** [comment]
As we don't want to confuse the students who submit, we have put tutorial in [this wiki](https://github.com/jtr13/cc19/wiki/Tutorial-for-maintainers).

**Comment by jtr13** [comment]
Wow, fantastic.  I think we should schedule a meeting of all the maintainers. We can discuss by email.
